### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by willhains** [playframework/play1#1366]
Please add support for Java 17 (LTS).

The previous LTS release (Java 11) will end support in September 2023.

**Comment by cies** [comment]
Java 14 with Play 1.6.0 is what we use, and it is the highest possible Java version afaik. I wonder what is making it impossible to use Java versions >14? Is it the dependencies, the Play1 code itself, or both?

**Comment by cies** [comment]
From [this PR](https://github.com/playframework/play1/pull/1345) I learned that an Eclipse JDT Core upgrade should allow Java 15.

**Comment by tomparle** [comment]
Hi, current version of Play currently supports Java up to 16.

Support for version 17 will come, when I have some time for it unless someone else is faster :-)

**Comment by tazmaniax** [comment]
Hi, I've had a [pull request](https://github.com/tazmaniax/play1/pull/9) on my Play1 fork that I'm running on JDK 16 on production (Heroku) and locally on JDK 17 without any issue. It only support JDK 16 source because waiting on Eclipse JDT core update to support JDK 17. The dependencies are the latest possible as of today and all tests pass except for some "errors" and "routing" tests that I've been unable to resolve and I've commented out for the moment. I haven't raised a pull request against the main Play1 repo because I couldn't resolve these test issues

**Comment by cies** [comment]
@tazmaniax Nice set of version bumps as well!

**Comment by tazmaniax** [comment]
FYI my [pull request](https://github.com/tazmaniax/play1/pull/9) now supports JDK 17 source with recent release of Eclipse JDT Core 3.28.0

**Comment by sbeigel** [comment]
Any news for the JDK 17 support?

**Comment by tazmaniax** [comment]
@sbeigel my [pull request](https://github.com/tazmaniax/play1/pull/9) is working well in production with JDK 17 source code support. As per my previous comment above, I have not created a pull request for the main line Play1 repo because I've had to comment out some specific tests that may not be to everyone's satisfaction and I haven't had any time to resolve them.

**Comment by sbeigel** [comment]
I tried your code with some rather large web applications and no problems so far! Great and thank you :)

It would be great if the maintainers could chime in to get this merged soon.

Same goes btw for #1354 which makes the current master branch unusable for production.

**Comment by tazmaniax** [comment]
@sbeigel I've gone ahead and applied #1354 to my JDK 17 compatible Play1 [pull request](https://github.com/tazmaniax/play1/pull/9).

**Comment by willhains** [comment]
🎉 Thank you! ❤️
