### ISSUE TITLE
Update selenium to 2.53

### ISSUE THREAD

**Issue by xael-fry** [playframework/play1#986]

**Comment by gslowikowski** [comment]
BTW, you can fix the bug, I reported here https://groups.google.com/forum/#!topic/play-framework/iUOysRVpJwg.

Before Play! 1.3.0 original `selenium-api.js` was modified to use square brackets for variables, because Play! would try to resolve all variables in braces when rendering Selenium test template:
```js
    var match = stringResult.match(/\$\[\w+\]/g);
```
Check [source](https://github.com/playframework/play1/blob/7c6e3bc10984f8ef8183492387122d807bcf566e/modules/testrunner/public/test-runner/selenium/scripts/selenium-api.js#L2443).

After [the change](https://github.com/playframework/play1/commit/b1ed896085d52203d8dfa1a372268dab3009a520) this fix was accidentally removed:
```js
    var match = stringResult.match(/\$\{\w+\}/g);
```
and since then variables in Selenium tests didn't work. Check [source](https://github.com/playframework/play1/blob/b1ed896085d52203d8dfa1a372268dab3009a520/modules/testrunner/public/test-runner/selenium/scripts/selenium-api.js#L2549)


Please, **restore it** now.

**Comment by xael-fry** [comment]
Issue created for this issue #988

**Comment by xael-fry** [comment]
Done in PR #989
