### ISSUE TITLE
Do not swallow cause of exception

### ISSUE THREAD

**Issue by asolntsev** [playframework/play1#993]
We can see the following construction in many places in Play 1 framework:

```java
try {
 ...
}
catch (Exception ex) {
  throw new UnexpectedError("Could not do something");
}
```

Such code is pretty bad because the original exception `ex` gets lost. 

We should always re-throw the original exception:

```java
throw new UnexpectedError("Could not do something", ex);
```

or at least log it.

**Comment by asolntsev** [comment]
Done in branch 1.4.x for many cases (but unfortunately not for all).

**Comment by selangley** [comment]
While it is a good philosophy to not swallow exceptions, the code now no longer executes the original author's intent.

The code is meant to identify whether the current start tag is a GroovyInlineTag, i.e., an #{if...} #{else...} or #{list...}

If it is not, then the code should swallow the exception and continue to the next section to note other characteristics of the tag.
 
You should probably put back the original exception handler of:

// do nothing here

And add more code comments so that future maintainers have a clearer understanding of what's happening in this method.

**Comment by asolntsev** [comment]
@selangley I agree, I enabled too much logging. I am going to remove some of them.

**Comment by xael-fry** [comment]
@asolntsev It is the problem I talked you about, try to keep your change and avoiding the exception, but cannot find a way to do it for now
